name = "GaussianDispersion"
uuid = "7b7cc4e3-398b-4c6b-b3a7-b5804ff909e2"
authors = ["tcarion <tristan.carion@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
Parameters = "0.12"
DocStringExtensions = "0.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
